name: system
description: A new Flutter project.
version: 0.0.18
homepage: system
publish_to: none

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  kit:
    git:
      url: https://github.com/clong1995/proj-kit.git
      path: kit
  package:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: package
  rpx:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: rpx
  ui_adapt:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_adapt
  ui_table:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_table
  guid:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: guid
  device:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: device
  ui_page_view_item:
    git:
      url: https://github.com/clong1995/flutter_ui.git
      path: ui_page_view_item
  #网络图片缓存
  cached_network_image: ^3.4.1
  #本地存储
  shared_preferences: ^2.3.5
  #加解密
  encrypt: ^5.0.3
  #设备信息
  device_info_plus: ^11.2.1
  #摘要
  crypto: ^3.0.6
  #http
  http: ^1.2.2
  #toast
  toastification: ^2.3.0
  #唯一id
  xid: ^1.2.1
  dropdown_button2: ^2.3.9
  jiffy: ^6.3.2
  file_picker: ^8.1.7
  # excel: ^4.0.3
  package_info_plus: ^8.1.3
  path_provider: ^2.1.4
  path: ^1.9.0
  window_manager: ^0.4.3
  screen_retriever: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
